# Generated by Django 3.0.4 on 2020-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitternetwork',
            name='display_name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='twitternetwork',
            name='network_status',
            field=models.CharField(default='started', max_length=150),
        ),
        migrations.AlterField(
            model_name='twitternetwork',
            name='search_terms',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
